### ISSUE TITLE
Failed to load interface for ‘Foreign.CUDA.Path’

### ISSUE THREAD

**Issue by Haskell-mouse** [tmcdonell/nvvm#1]
XUbuntu 16.04 
It is strange error - cuda-0.8.0.0 have been built without errors, and i can load this module in ghci. 
The same error was with package cufft. 
With cufft error had diisappeared when i changed commit ver from "cecc8bdfe857463773635010ac350b80d0fe99e3" to last in my stack.yaml 

But nvvm i can build only without importing Foreign.CUDA.Path module (i have written paths by hand).

**Comment by Haskell-mouse** [comment]
Writing path by hand is ugly solution, but i have small time to do my own task (vigner-wille distribution) :-(

**Comment by tmcdonell** [comment]
That seems very strange... can you paste your `stack.yaml` file and I'll try building on my machine with that?

**Comment by tmcdonell** [comment]
The travis-ci machine is a ubuntu-14.04 box, so I would expect would run fine on your box... \\:

**Comment by Haskell-mouse** [comment]
resolver: lts-8.23
packages:
- '.'
- location: 
    git:    https://github.com/AccelerateHS/accelerate-io.git
    commit: 6e6fd16a380af2054ab6abe5fd2423e19dda783c
  extra-dep: true 
- location:
    git:    https://github.com/AccelerateHS/accelerate-fft.git
    commit: 413c7a170d592165f20e6e114afbd917b6569a3e
  extra-dep: true
- location:
    git:    https://github.com/AccelerateHS/accelerate.git
    commit: af7137f1c9aabc95d23ef2f480ec55d4b53e95b7
  extra-dep: true

- location:
    git:    https://github.com/AccelerateHS/accelerate-llvm.git
    commit: e1699b2f1f5c61b614121ef38d15f2f8da5c4b1d
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'
- location:
    git:    https://github.com/tmcdonell/cuda.git
    commit: 1bff17152088384b71a439b01ec993a54e2618c9
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/cufft.git
    commit: fc78baea2b44784719925c7ac32a6b8ff910dab5
  extra-dep: true
#- location: 
#    git:    https://github.com/tmcdonell/nvvm.git
#    commit: 9f1225801320c5b4e6a5e6dc656227d1c8522ab0
#  extra-dep: true
- location: nvvm-master
  extra-dep: true
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)

extra-deps: [llvm-hs-4.1.0.0,chaselev-deque-0.5.0.5,llvm-hs-pure-4.1.0.0]
# Override default flag values for local packages and extra-deps
flags:
      accelerate-fft: 
                     llvm-ptx: true
                     llvm-cpu: true 
      llvm-hs:                
                     shared-llvm: true 
      accelerate:
                     unsafe-checks: false
                     bounds-checks: false
                     debug: false
                     internal-checks: false
      accelerate-llvm:
                     debug: false
                     chase-lev: true
      accelerate-llvm-native:
                     debug: false
      accelerate-llvm-ptx:
                     debug: false
                     nvvm: false
build:
      library-profiling: false
      executable-profiling: false
ghc-options: 
            wigner: "-with-rtsopts=-n2M -with-rtsopts=-A64M"
extra-package-dbs: []

**Comment by Haskell-mouse** [comment]
[stack.txt](https://github.com/tmcdonell/nvvm/files/1225222/stack.txt)

**Comment by tmcdonell** [comment]
I assume that the `nvvm-master` location was a local checkout? I switched it to the (commented out) github location tmcdonell/nvvm@9f1225801320c5b4e6a5e6dc656227d1c8522ab0. Then, `stack build nvvm` worked for me.

Maybe try deleting the `.stack-work` directory, or `stack clean`?

**Comment by Haskell-mouse** [comment]
I have tried to delete .stack-work without success. 
Just now i have tried to delete nvvm dir and to do git clone : 

suhareva@lab278ws:~/Rinat$ git clone https://github.com/tmcdonell/nvvm.git
Cloning into 'nvvm'...
remote: Counting objects: 241, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 241 (delta 3), reused 5 (delta 1), pack-reused 232
Receiving objects: 100% (241/241), 51.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (127/127), done.
suhareva@lab278ws:~Rinat$ cd nvvm/
suhareva@lab278ws:~Rinat/nvvm$ cp stack-8.0.yaml stack.yaml
suhareva@lab278ws:~Rinat/nvvm$ stack build
cuda-0.8.0.0: configure
cuda-0.8.0.0: build
cuda-0.8.0.0: copy/register
nvvm-0.8.0.0: configure
[1 of 1] Compiling Main             ( /home/suhareva/Rinat/nvvm/Setup.hs, /home/suhareva/Rinat/nvvm/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
             
/home/suhareva/Rinat/nvvm/Setup.hs:31:1: error:
    Failed to load interface for ‘Foreign.CUDA.Path’
    Use -v to see a list of the files searched for.
Completed 2 action(s).

--  While building package nvvm-0.8.0.0 using:
      /usr/bin/ghc --make -odir /home/suhareva/Rinat/nvvm/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -hidir /home/suhareva/Rinat/nvvm/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup -i -i. -package=Cabal-1.24.2.0 -clear-package-db -global-package-db -package-db=/home/suhareva/.stack/snapshots/x86_64-linux/lts-9.0/8.0.2/pkgdb /home/suhareva/Rinat/nvvm/Setup.hs -o /home/suhareva/Rinat/nvvm/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup
    Process exited with code: ExitFailure 1
suhareva@lab278ws:~/Rinat/nvvm$ 

Very strange...

**Comment by tmcdonell** [comment]
What version of stack/cabal do you have? I get:

```sh
$ stack --version
Version 1.5.0, Git revision 63267f94d7c819cbecc2d59aa259d17240838e43 (4845 commits) x86_64 hpack-0.17.1

$ cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library
```

Also just checking that the following works:

```sh
$ stack install cuda
$ stack exec ghci
ghci> import Foreign.CUDA.Path
ghci> cudaBinPath
```

**Comment by Haskell-mouse** [comment]
i tried the last action yesterday and it worked fine... 

suhareva@lab278ws:~/Rinat/nvvm$ stack exec ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> import Foreign.CUDA.Path
Prelude Foreign.CUDA.Path> cuda
cudaBinPath      cudaIncludePath  cudaInstallPath  cudaLibraryPath
Prelude Foreign.CUDA.Path> cudaBinPath 
"/usr/bin"
Prelude Foreign.CUDA.Path>

**Comment by Haskell-mouse** [comment]
$ stack  --version 
Version 1.1.2 x86_64 hpack-0.14.1

$ cabal --version 
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library

**Comment by tmcdonell** [comment]
Try upgrading `stack`? That is something easy to try at least...

**Comment by Haskell-mouse** [comment]
I have upgraded stack (to 1.5.1 by "wget -qO- https://get.haskellstack.org/ | sh"). 
And, to my surprise, it works ! At least building of nvvm is successful....

**Comment by Haskell-mouse** [comment]
And building of my project is successful too. 
Thank you very much!  
I didn't think that old version of stack can be cause of such error.

**Comment by tmcdonell** [comment]
Very strange indeed! Glad we got it working though, good luck with your project (:
